### ISSUE TITLE
Testing metaMS

### ISSUE THREAD

**Issue by jsaintvanne** [rwehrens/metaMS#10]
Hi,

I'm working with @yguitton on W4M and we have just update our workflow with your tool "metaMS". But we are actually facing a problem and we hope that you could answer us about it : 

the problem is about tests, we compare our output on peakTable but these peakTable are not really the same whereas we executed exactly the same command line... I have just seen that in your test you compare the number of columns and lines, the names but not the results in your peakTable. 
So is it normal that numbers in peakTable changed ? Is it possible to explain that changes ?

Thanks for your answer !

Cheers,
Julien

**Comment by yguitton** [comment]
@jsaintvanne  I close the issue? All tests are passing now, right? If needed reopen it
